/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controleObra;

import banco.ServicoBancoObra;
import banco.ServicoBancoParecer;
import classes.*;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author suporte
 */
public class Frm_CadbraParecer extends javax.swing.JFrame {

    public Frm_CadbraParecer() {
        initComponents();
        limparTela();
    }
    
    public ServicoObra srvObra;
    public Obra obra;
    

    private void limparTela(){
        jpParecer.setVisible(false);
        jtTitulo.setText("");
        jtAutor.setText("");
        jtTitulo.requestFocus();
    }
    
    private void limparTelaParecer(){
        jtParecerista.setText("");
        jtParecer.setText("");
        jtData.setText("");
        jtHora.setText("");
        
        Date d = new Date();
        
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat hf = new SimpleDateFormat("HH:mm:ss");
        
        jtData.setText(df.format(d));
        jtHora.setText(hf.format(d));
        jtParecerista.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpObra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbAddParecer = new javax.swing.JButton();
        jpParecer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtParecerista = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtParecer = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jtData = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtHora = new javax.swing.JTextField();
        jbAddPacerObra = new javax.swing.JButton();
        jbNovaObra = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Castro de Obras / Parecer");
        setAlwaysOnTop(true);

        jLabel1.setText("Título");

        jLabel2.setText("Autor");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Obra");

        jbAddParecer.setText("Adicionar Parecer");
        jbAddParecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddParecerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpObraLayout = new javax.swing.GroupLayout(jpObra);
        jpObra.setLayout(jpObraLayout);
        jpObraLayout.setHorizontalGroup(
            jpObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObraLayout.createSequentialGroup()
                .addGroup(jpObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpObraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpObraLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtAutor))
                            .addGroup(jpObraLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpObraLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel3))
                    .addGroup(jpObraLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jbAddParecer)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jpObraLayout.setVerticalGroup(
            jpObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpObraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jpObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAddParecer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Pareceres");

        jLabel5.setText("Parecerista");

        jLabel6.setText("Parecer");

        jtParecer.setColumns(20);
        jtParecer.setRows(5);
        jScrollPane1.setViewportView(jtParecer);

        jLabel7.setText("Data");

        jLabel8.setText("Hora");

        jbAddPacerObra.setText("Adicionar Parcer");
        jbAddPacerObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddPacerObraActionPerformed(evt);
            }
        });

        jbNovaObra.setText("Nova Obra");
        jbNovaObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovaObraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpParecerLayout = new javax.swing.GroupLayout(jpParecer);
        jpParecer.setLayout(jpParecerLayout);
        jpParecerLayout.setHorizontalGroup(
            jpParecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpParecerLayout.createSequentialGroup()
                .addGroup(jpParecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpParecerLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel4))
                    .addGroup(jpParecerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpParecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpParecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtParecerista)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)))
                    .addGroup(jpParecerLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtData, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpParecerLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jbAddPacerObra)
                        .addGap(36, 36, 36)
                        .addComponent(jbNovaObra)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jpParecerLayout.setVerticalGroup(
            jpParecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpParecerLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jpParecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtParecerista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpParecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpParecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jpParecerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAddPacerObra)
                    .addComponent(jbNovaObra))
                .addGap(24, 24, 24))
        );

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpParecer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jpObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSair)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jpObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpParecer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jbSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovaObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovaObraActionPerformed
       srvObra.adicionaObra(obra);
       srvObra.persitirBanco(obra);
       jbAddParecer.setEnabled(true);
       limparTela();
    }//GEN-LAST:event_jbNovaObraActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbAddParecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddParecerActionPerformed
        if (jtTitulo.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Entre com o título da obra!");
            jtTitulo.requestFocus();
            return;
        }
        
        if (jtAutor.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Entre com o autor da obra!");
            jtAutor.requestFocus();
            return;
        }
         
        jpParecer.setVisible(true);
        limparTelaParecer();
        jbAddParecer.setEnabled(false);
        
        obra = new Obra();
        obra.setTitulo(jtTitulo.getText());
        obra.setAutor(jtAutor.getText());
        
    }//GEN-LAST:event_jbAddParecerActionPerformed

    private void jbAddPacerObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddPacerObraActionPerformed
        if (jtParecerista.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Entre com o parecerista!");
            jtParecerista.requestFocus();
            return;
        }
        
        if (jtParecer.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Entre com o parecer!");
            jtParecerista.requestFocus();
            return;
        }

        if (jtData.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Entre com a data!");
            jtData.requestFocus();
            return;
        }
        
        if (jtHora.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Entre com a hora!");
            jtHora.requestFocus();
            return;
        }
        
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat hf = new SimpleDateFormat("HH:mm:ss");
        
        Date dt;
        
        Parecer parecer = new Parecer();
        parecer.setParecerista(jtParecerista.getText());
        parecer.setConteudo(jtParecer.getText());
        
        try {
            dt = df.parse(jtData.getText());
        }
        catch (Exception e){
            dt = new Date();
        }
         
       parecer.setData(dt);
       
        try {
            dt = hf.parse(jtHora.getText());
        }
        catch (Exception e){
            dt = new Date();
        }
        
        parecer.setHora(dt);
        
        obra.adicionaParecer(parecer);
        
        limparTelaParecer();
    }//GEN-LAST:event_jbAddPacerObraActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_CadbraParecer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAddPacerObra;
    private javax.swing.JButton jbAddParecer;
    private javax.swing.JButton jbNovaObra;
    private javax.swing.JButton jbSair;
    private javax.swing.JPanel jpObra;
    private javax.swing.JPanel jpParecer;
    private javax.swing.JTextField jtAutor;
    private javax.swing.JTextField jtData;
    private javax.swing.JTextField jtHora;
    private javax.swing.JTextArea jtParecer;
    private javax.swing.JTextField jtParecerista;
    private javax.swing.JTextField jtTitulo;
    // End of variables declaration//GEN-END:variables
}
